### PR TITLE
Add veterancy skill bonuses.

### PR DESCRIPTION
**Pull request by brunns**

### CODE REVIEW

**Comment by brunns** [comment]
Any thoughts, @jimstorch?

**Comment by jimstorch** [comment]
Hey Simon.  I may revisit it someday but, TBH, I haven't played in quite a while.

**Comment by brunns** [comment]
Fair enough. Feel free to add me as a collaborator if you don't think you'll be able to find the time - and if you want to!

**Comment by brunns** [comment]
Test veterans in https://bit.ly/4a2i57V - look OK?

**Comment by jimstorch** [comment]
That is really cool, Simon.

**Pull request merged**
