### PR TITLE
Profession balance

### PR DESCRIPTION
**Pull request by brunns**
I don't know about you, but I find I need a lot more federal agents than I do programme managers. This PR allows different numbers of characters to be generated for each profession, or even for some professions to be omitted entirely.

### CODE REVIEW

**Comment by brunns** [comment]
Moving the professions into data would allow us to hang other things from it - all the `if profession ==` stuff from `Need2KnowCharacter`' `__init__` could be pulled out, for example, which feels like a nice idea. We could also add some sort of equipment stuff in there.

**Comment by brunns** [comment]
That last commit pulls lots of profession stuff into data. I'm happy to remove it if you preferred things as they were! Obviously I like it though. ;-)

**Comment by jimstorch** [comment]
What would you think of expanding the command line to something like;
`$ generator.py --type combat --name "Green Beret" --count 24 --out "Bravo Company.pdf"`

**Comment by brunns** [comment]
Do you mean tagging the professions, and including only professions matching the `type` tag? Yeah, that could be very nice. Want me to take a run at it?

**Comment by brunns** [comment]
I was thinking of adding some equipment tags, too perhaps. 'unarmed', 'handgun', 'infantry' and 'heavy-military' or something like that?

**Update**: Ah, page 85 of the Agent's Handbook would be a good start for the tags and what equipment they imply.

**Comment by jimstorch** [comment]
Have a general profession from the JSON file like `--type police` and then specify what to actually fill in on the character sheet with another switch `--label "Homicide Detective"`.  My example above used `--name` but that's probably a poor choice.

**Comment by brunns** [comment]
Are you thinking that a type would apply to exactly one profession? If so, it might be easier to just use the profession's name:

     ./generate.py --type "Police Officer" --label "LAPD" --count 24 --output "The Los Angeles Police.pdf"

Would that work?

**Comment by jimstorch** [comment]
Yep.  I would probably change the types to single words in the JSON (if possible) to reduce the need for quotes.

**Comment by brunns** [comment]
Hmmmm. I think the profession names are better as they are for the existing, generate everything case. So I could change the existing data so the professions have a one-word, lower case name (a.k.a type) *and* a default label. 

* If a type is provided at the command line, only that profession is generated, and we'd omit the TOC.
* If a label is provided, that's used instead of the profession's default label. (If a label but no type is provided, it'll come out weird, but no harm really.)
* If a count is provided, that many of each profession will be generated. (Again, makes most sense if a type is provided, but no harm done either way.)

**Comment by jimstorch** [comment]
True. I didn't consider losing the long-form of the profession.  I do like the idea of "I need six cops for my 'Assault on Precinct 13' one-shot."

**Comment by brunns** [comment]
Absolutely. I'll have a go.

And next on the roadmap after selective generation, and equipment, maybe a web version. Hee hee.

**Pull request merged**
