### PR TITLE
Add equipment kits.

### PR DESCRIPTION
**Pull request by brunns**
Very much still work in progress for now.

### CODE REVIEW

**Comment by brunns** [comment]
Two questions, @jimstorch. As per "Tools of the Trade" page 85 of the Agent's Handbook, agent's have a separate list of gear which they usually leave in the boot of the car. Do we want to ignore these items, include them, or include them asterisked or something to point out that they aren't habitually carried?

Secondly, occasionally "Tools of the Trade" says an agent may carry one item **or** another. Should we give them both, neither, or do we want to give them one at random?

Once those things are sorted, I _think_ it'll just be a matter of extending `equipment.json` with gear for some other professions - all those listed in "Tools of the Trade" plus soldiers and marines at least, I'm thinking. I'm not sure I can be bothered with equipping Project Managers with post-its, sharpies and JIRA instances, though. ;-)

**Comment by jimstorch** [comment]
The greater specificity, the more narrow the application.  I would limit it to what they are going to be carrying in Spooky Building given five minutes notice.  Building the field office is the GM's job.

**Comment by brunns** [comment]
Fair enough. As you can see, the options are there now. We could remove them, or we could just not use them in the equipment kits.

**Comment by brunns** [comment]
Do give this a try - so far, only agents have kit specified - and see what you think.

Right, I have a hideous rebase to get on with. Wish me luck.

**Comment by brunns** [comment]
I'm sure there's plenty of room for tweaking who is equipped with what, but I think this PR is ready to go if you're OK with it in general.

**Comment by brunns** [comment]
Yay! Thank you.

**Comment by jimstorch** [comment]
I finally got a chance to look at the new PDF (I didn't have a live copy installed anywhere, as it's been a while since I've done any TTRPG gaming).  The equipment list is really well implemented, Simon.  Thanks.

**Comment by brunns** [comment]
Thanks. I'm glad you like it. I'm not 100% sure about the things I've actually equipped characters with, though, so I'd be happy to change anything.

Also, happy to talk you through the data structures if they aren't 100% obvious.

**Comment by jimstorch** [comment]
One feature I was kicking around came from listening to Role Playing Public Radio who were using the pregens for some of their DG sessions.  The players were failing a lot of rolls as their skills were based on freshly-minted characters, but a one-shot may call for more veteran agents, so have an option to have age affect the character;
`
skill_bonus = randint( (0, (character_age - 21 ) * 4)) # Add to a learned skill (assuming four skill-ups per year) 
age_penalty = randint(0, (character_age - 21)) # Deduct from physical skills
`
The numbers would be re-rolled for each application.  Something like that.  It would need tweaking.

**Comment by brunns** [comment]
Sounds cool. I'll raise this as a feature request issue, along with a couple of ideas I have.

**Comment by brunns** [comment]
BTW, do you want me to host some examples and post a [reddit](https://www.reddit.com/r/DeltaGreenRPG/) link, or do you want to do that?

**Comment by jimstorch** [comment]
Go for it.  You deserve the credit.

**Comment by brunns** [comment]
Done! https://www.reddit.com/r/DeltaGreenRPG/comments/qh1t3n/pregenerated_delta_green_characters_now_with/

**Comment by brunns** [comment]
I just noticed that reddit filtered out that post. Sigh. Perhaps you can post it after all? The new PDFs are [here](https://bit.ly/3mlQCZ8).

**Comment by jimstorch** [comment]
Weird, it flat out deleted your post.  I added and update to the top of the
original thread:

https://old.reddit.com/r/DeltaGreenRPG/comments/5gmt9f/eight_hundred_victims_for_your_delta_green/

**Pull request merged**
